version: "3.9"
services:
  api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/app
  
  pgadmin:
    links:
      - postgres:postgres
    image: dpage/pgadmin4:7.1
    ports:
      - 8080:80
    volumes:
      - /data/pgadmin:/root/.pgadmin
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  postgres:
    image: postgres:13.11
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /data/minio:/data/minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: minio server /data/minio --console-address :9001